PolymeshAssociation/polymesh-local

.vscode/settings.json
package.json
scripts/build-uis.ts
src/base.ts
src/commands/configure.ts
src/commands/start.ts
src/common/containers.ts
src/common/tooling.ts
src/common/util.ts
src/consts.ts
src/local/docker-compose.yml
src/local/mesh.Dockerfile.template
yarn.lock

Add support for 5.0.2 chain. Also improves config by providing a preset "bundle" of services, while leaving the choice of specific tags as an advanced option
None
✅ Closes: [DA-365](https://polymesh.atlassian.net/browse/DA-365)

feat: 🎸 Add support for 5.0.2 chains

---

package.json
scripts/generate-snapshot.ts

some references were for the old polymathnetwork github. This updates them to use PolymeshAssociation instead
N/A
N/A

feat: 🎸 update github reference to the new repository

---

.github/workflows/main.yml

Update the release token to a new ENV.
@prashantasdeveloper are we able to use the one for the SDK, or should we make a new one for this project? I think you updated the SDK and want to be consistent.
I update the ENV here to match the SDK, but we still need to set it for this repo.
N/A

feat: 🎸 update github release token env

---

src/commands/configure.ts
src/consts.ts

Bumps default to latest versions of services.
When testing I found my custom signer settings got over written. Now they get preserved

Bump default versions

---

README.md

Update instructions to install from correct repo
None
N/A
- [ x] Updated the Readme.md (if required) ?

docs: ✏️ update readme to reference the association's npm repo

---

src/common/util.ts

create target directory if it doesn't exist when downloading a file
None
[DA-429](https://polymesh.atlassian.net/browse/DA-429)

fix: 🐛 remote snapshots when local directory is not present

---

src/base.ts
src/commands/configure.ts
src/commands/start.ts
src/consts.ts

Lets users select 5.1.0 chain version without needing to manually figure out what version of all the services to use
None

feat: 🎸 add chain v5.1.0 config values

---

src/local/docker-compose.yml

on linux the domain needs to be explicitly enabled
Needed for [DA-376](https://polymesh.atlassian.net/browse/DA-376)

feat: 🎸 allow rest api to use host.docker.internal on linux

---

src/common/containers.ts

Docker uses the local cache by default, usually it works since image _should_ be immutable, but that doesn't apply to `latest`
None

fix: 🐛 pull in images when using `latest` version flag

---

src/local/docker-compose.yml
src/local/pg-extensions.sh

SubQuery was failing due to not having the extension in its DB

fix: 🐛 add pg extensions so newer SubQuery version work

---

src/commands/configure.ts
src/commands/start.ts
src/common/containers.ts
src/consts.ts

Adds a new config bundle, cleans up syntax, and lets us test against the truly latest release
n/a
n/a

feat: 🎸 add 5.1.3 and pull from develop for latest

---

src/base.ts
src/consts.ts

Adds config values for chain v5.2.0 with compatible version of other services
NA
NA

feat: 🎸 add chain v5.2.0 config values

---

CHANGELOG.md
README.md
package.json
src/common/containers.ts
src/consts.ts
src/local/schemas/polymesh_schema_5.1.0.json
src/local/schemas/polymesh_schema_5.1.3.json
src/local/schemas/polymesh_schema_5.2.0.json

Sets `fiveTwoZeroConfig` as  the default config. Also, updates the compatible service versions for 5.2.0 config
NA

feat: 🎸 Make 5.2.0 version as default version

---

src/consts.ts

Update SQ and REST API version compatible with chain 5.3.0
NA
DA-563

feat: 🎸 Update compatible REST API and SQ version for 5.3.0

---

src/consts.ts

Updates SQ version compatible with 5.3.0 testnet chain
NA
DA-586

feat: 🎸 Update latest SQ compatible with 5.3.0 chain

---

src/commands/start.ts
src/common/graphql.ts
src/consts.ts
src/local/docker-compose.yml

add native GraphQL at `http://localhost:3009`
[DA-553](https://polymesh.atlassian.net/browse/DA-553)
[DA-619](https://polymesh.atlassian.net/browse/DA-619)
[DA-553]: https://polymesh.atlassian.net/browse/DA-553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DA-619]: https://polymesh.atlassian.net/browse/DA-619?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: 🎸 add SQ native GraphQL on :3009

---

src/consts.ts

Update latest stable REST API and SQ version compatible with 5.3.0
NA
DA-592

feat: 🎸 Update latest REST API and SQ version with 5.3 version

---

src/consts.ts

Make 5.3.0 as default polymesh-local version
NA
DA-593

feat: 🎸 Make 5.3.0 as default version

---

src/local/schemas/polymesh_schema_5.4.0.json

feat: 🎸 add 5.4.0 schema file

---

src/consts.ts

Update REST and SQ to support 5.4 Polymesh
NA
DA-688

fix: 🐛 update REST and SQ to support 5.4 Polymesh

---

src/common/containers.ts
src/consts.ts

Make 5.4.0 as default version
NA
DA-734

feat: 🎸 Make 5.4.0 as default version

---

README.md
src/common/chain.ts
src/common/containers.ts
src/common/util.ts
src/consts.ts
src/local/docker-compose.yml
src/local/schemas/polymesh_schema_6.0.0.json

Adds chain 6.0 support
None
[DA-810](https://polymesh.atlassian.net/browse/DA-810)
[DA-810]: https://polymesh.atlassian.net/browse/DA-810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: 🎸 add 6.0 chain

---

src/common/containers.ts
src/consts.ts

Update SDK and REST-API to major versions
NA
NA

feat: 🎸 Update SDK and REST-API image versions

---

src/common/containers.ts

handle no service case with compose v2

fix: 🐛 handle no service case with compose v2
